version: '3'
services:
   db:
      image: unch-db
      networks:
        - backend
   app:
      depends_on:
         - db
      build: ./app
      image: unch-node
      volumes:
        - ./app:/app
      networks:
        - backend
      restart: always
      environment:
        PORT: 8080
        DB: "db"
        DB_PORT: 27017
   refresher:
      depends_on:
        - db
        - asterisk
      build: ./refresher
      image: unch-refresher
      networks:
        - backend
      restart: always
      environment:
        PYTHONUNBUFFERED: 1
        DB_HOST: "db"
        DB_PORT: 27017
        DB_NAME: "unch"
   asterisk:
      build: ./refresher/asterisk
      image: unch-asterisk
      volumes:
        - ./refresher/asterisk-config/extensions.conf:/etc/asterisk/extensions.conf
        - ./refresher/asterisk-config/sip.conf:/etc/asterisk/sip.conf
        - ./refresher/asterisk-config/manager.conf:/etc/asterisk/manager.conf
        - ./refresher/asterisk-config/confbridge.conf:/etc/asterisk/confbridge.conf
        - ./refresher/asterisk-config/musiconhold.conf:/etc/asterisk/musiconhold.conf
        - ./refresher/agi/eagi.py:/var/lib/asterisk/agi-bin/eagi.py
      networks:
        - backend
      restart: always
   snowboy:
      build: ./refresher/snowboy
      image: skiptheline/snowboy
      networks:
        - backend
      restart: always
networks:
  backend:
